version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - internal
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./symfony:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - internal
    depends_on:
      - php
      - mysql
  php:
    container_name: php
    build:
      context: ./php
      dockerfile: ./Dockerfile
    environment:
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./symfony:/var/www/html
    networks:
      - internal
    depends_on:
      - mysql
  vue:
    container_name: vue
    build:
      context: ./vue
      dockerfile: ./Dockerfile
    volumes:
      - './vue:/app'
    ports:
      - '8081:8080'
    networks:
      - internal
    depends_on:
      - php
networks:
  internal:
    driver: bridge